apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-ci-app
  template:
    metadata:
      labels:
        app: java-ci-app
    spec:
      containers:
      - name: java-container
        image: sahana1478/java-docker-ci:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
